version: "3.8"
services:
  fastapi:
    build: .
    depends_on:
      - postgres_db
    image: meetbariya/aniquotes:1.0
    entrypoint: /opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:ro

  postgres_db:
    container_name: postgres_db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:  
      - postgres-db:/var/lib/postgresql/data/
volumes:
  postgres-db: